package com.amperus.prospection.adapters.secondary.rncprovision;

enum TypeVoieAbbreviation {
    ABE("abbaye"),
    ACH("ancien chemin"),
    AER("aérodrome, aéroport"),
    AIRE("aire"),
    ALL("allée"),
    ANSE("anse"),
    AR("ancienne rue"),
    ARC("arcade"),
    ART("ancienne route"),
    AUT("autoroute"),
    AV("avenue"),
    BAL("balcon"),
    BAS("bastion"),
    BASE("base"),
    BAT("bâtiment"),
    BCH("bas chemin"),
    BCLE("boucle"),
    BD("boulevard"),
    BER("berge"),
    BOIS("bois"),
    BRC("brèche"),
    BRE("barrière"),
    BRG("bourg"),
    BRTL("bretelle"),
    BSTD("bastide"),
    BUT("butte"),
    CALE("cale"),
    CAMP("camp"),
    CAN("canal"),
    CAR("carrefour"),
    CARE("carrière"),
    CARR("carrè"),
    CASR("rne"),
    CAU("carreau"),
    CC("chemin communal"),
    CCAL("centre commercial"),
    CD("chemin départemental"),
    CEIN("ceinture"),
    CGNE("campagne"),
    CHE("chemin"),
    CHEM("cheminement"),
    CHEZ("chez"),
    CHI("charmille"),
    CHL("chalet"),
    CHP("chapelle"),
    CHS("chaussée"),
    CHT("château"),
    CITE("cité"),
    CLOS("clos"),
    COL("col"),
    COLI("colline"),
    COR("corniche"),
    CORO("coron"),
    COT("côte"),
    COTE("coteau"),
    COTT("cottage"),
    COUR("cour"),
    CPG("camping"),
    CR("chemin rural"),
    CRS("cours"),
    CST("castel"),
    CTR("contour"),
    CTRE("centre"),
    CVE("coursive"),
    CHV("chemin vicinal"),
    D("départementale"),
    DIG("digue"),
    DOM("domaine"),
    DSC("descente"),
    ECA("écart"),
    ECL("écluse"),
    EGL("église"),
    EN("enceinte"),
    ENC("enclos"),
    ENV("enclave"),
    ESC("escalier"),
    ESP("esplanade"),
    ESPA("espace"),
    FG("faubourg"),
    FON("fontaine"),
    FORM("forum"),
    FORT("fort"),
    FOS("fosse"),
    FRM("ferme"),
    GAL("galerie"),
    GARE("gare"),
    GBD("grand boulevard"),
    GPE("groupe"),
    GPL("grande place"),
    GPT("groupement"),
    GR("grande rue"),
    GRI("grille"),
    HAM("hameau"),
    HCH("haut chemin"),
    HIP("hippodrome"),
    HLE("halle"),
    HLG("halage"),
    HLM("hlm"),
    ILE("île"),
    ILOT("îlot"),
    IMM("immeuble"),
    IMP("impasse"),
    JARD("jardin"),
    JTE("jetée"),
    LD("lieu-dit"),
    LEVE("levée"),
    LOT("lotissement"),
    MAIL("mail"),
    MAIS("maison"),
    MAR("marché"),
    MAS("mas"),
    ML("moulin"),
    MTE("montée"),
    MUS("musée"),
    NTE("nouvelle route"),
    PAE("petite avenue"),
    PAL("palais"),
    PARC("parc"),
    PAS("passage"),
    PASS("passe"),
    PAT("patio"),
    PAV("pavillon"),
    PCH("petit chemin"),
    PERI("périphérique"),
    PIM("petite impasse"),
    PISTE("piste"),
    PKG("parking"),
    PL("place"),
    PLAN("plan"),
    PLCI("placis"),
    PLE("passerelle"),
    PLN("plaine"),
    PLT("plateau"),
    PN("passage à niveau"),
    PNT("pointe"),
    PONT("pont"),
    PORT("port"),
    POT("poterne"),
    PR("petite rue"),
    PRE("pré"),
    PROM("promenade"),
    PRQ("presqu'île"),
    PRT("petite route"),
    PRV("parvis"),
    PTA("petite allée"),
    PTE("porte"),
    PTTE("placette"),
    QU("quai"),
    QUA("quartier"),
    R("rue"),
    RAC("raccourci"),
    RAID("raidillon"),
    RDE("ronde"),
    REM("rempart"),
    RES("résidence"),
    RLE("ruelle"),
    RN("route nationale"),
    RNG("rangée"),
    ROC("rocade"),
    RPE("rampe"),
    RPT("rond point"),
    RTD("rotonde"),
    RTE("route"),
    RUELLETTE("ruellette"),
    RUETTE("ruette"),
    SEN("sentier"),
    SENTE("sente"),
    SQ("square"),
    STA("station"),
    STDE("stade"),
    TOUR("tour"),
    TPL("terre-plein"),
    TRA("traverse"),
    TRN("terrain"),
    TRT("tertre"),
    TSSE("terrasse"),
    VAL("vallée"),
    VC("voie communale"),
    VCHE("vieux chemin"),
    VEN("venelle"),
    VIA("via"),
    VLA("villa"),
    VLGE("village"),
    VOI("voie"),
    VR("vieille rue"),
    VTE("vieille route"),
    ZA("zone artisanale"),
    ZAC("zone aménagement concerté"),
    ZAD("zone aménagement différé"),
    ZI("zone industrielle"),
    ZONE("zone"),
    ZUP("zone à urbaniser en priorité");

    private final String fullForm;

    TypeVoieAbbreviation(String fullForm) {
        this.fullForm = fullForm;
    }
    
    public String getFullForm() {
        return fullForm;
    }

    public static String unAbbreviateIfNeeded(String word) {
        for (TypeVoieAbbreviation abbreviation : TypeVoieAbbreviation.values()) {
            if (abbreviation.name().equalsIgnoreCase(word)) {
                return abbreviation.getFullForm();
            }
        }
        return word;
    }
}
